webledger-project/webledger/urls.py
from django.contrib import admin
from django.urls import path
from ledger import views
#for invoice images
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    #url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('admin/', admin.site.urls),

    #ledger
    path('', views.home, name = 'home'),
    path('dealerform/', views.dealerform, name = 'dealerform'),
    path('ledger/<int:pk>/', views.ledger, name = 'ledger'),
    path('dealer/<int:pk>/', views.dealer, name = 'dealer'),
    path('user/', views.userpage, name = 'userpage'),
    path('expense/', views.roadexpense, name = 'roadexpense'),
    #report to convert in pdf
    path('dailytrans/', views.dailytrans, name = 'dailytrans'),

    #pdf rendering
    path('netbalpdf/', views.netbal_pdf_view, name = 'netbalpdf'),
    path('day_range_rec/', views.day_range_rec, name = 'day_range_rec'),
    path('cheque_alter/<int:ledger_no>/<int:pk>',views.cheque_alter,name='cheque_alter'),
    #AUTH
    path('login/', views.loginuser, name = 'loginuser'),
    path('logout/', views.logoutuser, name = 'logoutuser'),

]

# only in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.index_title = "Web Ledger"
admin.site.site_header = "Only Admin Area"

webledger-project/ledger/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.db.models.signals import post_save,post_delete

# Create your models here.
class Dealer(models.Model):
    name = models.CharField(unique=True, max_length=200)
    mob_num = models.IntegerField(unique=True, blank=True, null=True)
    address = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Collected_by(models.Model):
    name = models.CharField(max_length=50, blank=True)

    class Meta:
        verbose_name_plural = "Money Collected By"

    def __str__(self):
        return self.name


class Ledger(models.Model):
    date = models.DateTimeField("Date",auto_now_add=True)
    particulars = models.CharField("Particulars",max_length=100,blank=True)
    debit = models.PositiveIntegerField("Debit",blank=True, default=0)
    credit = models.PositiveIntegerField("Credit",blank=True, default=0)
    paymode = models.CharField("Payment Mode",max_length=25, choices=(('Cash','Cash'),
                                                       ('Cheque','Cheque'),
                                                       ('No Money Collected','No Money Collected'),))
    isChequeCleared = models.BooleanField(editable=False, blank=True, null=True)                                                   
    new_balance = models.IntegerField(editable=False)
    dr_cr = models.CharField("Dr/Cr",max_length=2,default='nil',editable=False)
    invoice = models.ImageField("Invoice",upload_to=None, blank=True)
    dealer = models.ForeignKey(Dealer,verbose_name="Dealer", null=True, on_delete=models.SET_NULL)
    balance = models.IntegerField(editable=False,default=0)
    dealer_ledger_number = models.IntegerField(editable=False,default=0)
    @property
    def cur_bal_calculator(self):
        prev = BrandNew.objects.get(dealer = self.dealer)
        return prev.balance + self.debit-self.credit

    @property
    def assign_dealer_ledger_number(self):
        prev = BrandNew.objects.get(dealer = self.dealer)
        return prev.ledger_number + 1

    @property
    def assign_dr_cr(self):
        if(self.new_balance<0):
            return "Cr"
        else:
            return "Dr"

    @property
    def assign_positive_balance(self):
        return abs(self.new_balance)

    collect_by = models.ForeignKey(Collected_by,verbose_name="Collected By", blank=True, null=True, on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
          self.new_balance = self.cur_bal_calculator
          self.dealer_ledger_number = self.assign_dealer_ledger_number
          self.balance = self.assign_positive_balance
          self.dr_cr = self.assign_dr_cr
          super(Ledger, self).save(*args, **kwargs)



    class Meta:
        db_table= "led"

class ViewDealer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    dealer = models.ManyToManyField(Dealer, related_name="dealer", blank= True)

    class Meta:
        verbose_name_plural = "Dealer Permission Area"

class RoadExpense(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    fooding = models.PositiveIntegerField(blank=True, default=0)
    fuel = models.PositiveIntegerField(blank=True, default=0)
    misc = models.TextField(blank=True)

    # def __str__(self):
    #     return self.user


class BrandNew(models.Model):
    dealer = models.ForeignKey(Dealer,on_delete=models.CASCADE)
    #dr_cr = models.CharField("Dr/Cr",max_length=10, default='', choices=(('Dr','Dr'),('Cr','Cr'),))

    balance = models.IntegerField(default=0)
    ledger_number = models.IntegerField(default=0)

def bal_one(sender, instance, **kwargs):
    if kwargs['created']:
        a = BrandNew(dealer = instance,balance = 0,ledger_number=0)
        a.save()


def update_bal_one(sender,instance,**kwargs):
    if kwargs['created']:

        a = BrandNew.objects.get(dealer = instance.dealer)

        a.delete()
        m = BrandNew(dealer = instance.dealer,balance = instance.new_balance,ledger_number = instance.dealer_ledger_number)
        m.save()
    if  not kwargs['created']:
        m = BrandNew.objects.get(dealer = instance.dealer)
        latest_ledger_number = instance.dealer_ledger_number
        cur_ledger_number = latest_ledger_number -1
        while(cur_ledger_number!=1):
            try:
                obj = Ledger.objects.get(dealer_ledger_number = cur_ledger_number,dealer = instanace.dealer)
            except:

                break
            cur_ledger_number-=1

        if cur_ledger_number == 1:
            prev = 0
        else:
            prev = Ledger.objects.get(dealer_ledger_number = cur_ledger_number-1,dealer= instance.dealer)
            prev = prev.new_balance
        i = cur_ledger_number
        debit = instance.debit
        credit = instance.credit
        new_balance = prev + debit - credit
        BN = BrandNew.objects.get(dealer = instance.dealer)
        BN.delete()
        BN.ledger_number = i-1
        BN.dealer = instance.dealer
        BN.balance = prev
        BN.save()
        led = Ledger(dealer = instance.dealer,debit = instance.debit,credit = instance.credit)
        led.save()
        BN = BrandNew.objects.get(dealer = instance.dealer)
        BN.delete()
        BN.dealer = instance.dealer
        BN.balance = new_balance
        BN.ledger_number = i
        BN.save()
        i = i+1

        prev = new_balance
        while(i!=latest_ledger_number):

            old = Ledger.objects.get(dealer_ledger_number = i,dealer=instance.dealer)
            #new = Ledger(dealer_ledger_number=i,debit=old.debit,credit=old.credit,collect_by=old.collect_by,dealer=instance.dealer,paymode=old.pay)
            old.delete()
            b = BrandNew.objects.get(dealer = instance.dealer)
            b.delete()
            b.dealer = instance.dealer
            b.ledger_number = i-1
            b.balance = prev
            b.save()
            old.paymode = 'Cheque'
            old.dealer_ledger_number = i
            old.save()
            prev = old.new_balance
            i = i+1
        Ledger.objects.get(dealer_ledger_number = latest_ledger_number,dealer = instance.dealer).delete()





post_save.connect(bal_one,sender = Dealer)
post_save.connect(update_bal_one,sender = Ledger)

webledger-project/ledger/forms.py
from django.forms import ModelForm
from .models import *

class LedgerForm(ModelForm):
    class Meta:
        model = Ledger
        fields = ['particulars', 'debit', 'credit', 'paymode', 'invoice', 'dealer', 'collect_by']



class DealerForm(ModelForm):
    class Meta:
        model = Dealer
        fields = '__all__'


class RoadExpenseForm(ModelForm):
    class Meta:
        model = RoadExpense
        fields = '__all__'

webledger-project/ledger/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import LedgerForm, DealerForm, RoadExpenseForm
from .decorators import unauthenticated_user, allowed_users, admin_only
from django.core.paginator import Paginator, EmptyPage

# for current date displaying in netbal_pdf_view
import datetime
from datetime import date, timedelta
#for rendering pdf
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa


#function for rendering pdf of dealer report
@login_required(login_url='loginuser')
@allowed_users(allowed_roles=['admin'])
def netbal_pdf_view(request):
    template_path = 'ledger/netbalpdf.html'
    a = BrandNew.objects.all()
    size = len(a)
    today = date.today()
    d4 = today.strftime("%d-%b-%Y")
    context = {'a':a,'size':size,'today':d4}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #if direct download needed uncomment line below
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

#function for rendering pdf of records in range of mentioned dates


def day_range_rec(request):
    if request.method == 'GET':
        return render(request,'ledger/dailytrans.html')

    else:
        template_path = 'ledger/day_range_rec.html'
        fromdate = request.POST.get('fromdate')
        todate = request.POST.get('todate')
        # To force selection of both the date fields
        if fromdate == "" or todate == "":
            context = {"error": "Please select both the fields"}
            return render(request,'ledger/dailytrans.html', context)

        # To ensure selected date range is valid
        today = date.today()
        d1 = today.strftime("%Y-%m-%d")
        tomorrow = today + timedelta(1)
        d2 =  tomorrow.strftime("%Y-%m-%d")
        if fromdate>todate or fromdate>d1 or todate>d2:
            context = {"error": "selected date range is invalid"}
            return render(request,'ledger/dailytrans.html', context)

        ledgers = Ledger.objects.raw('select * from led where date between "'+fromdate+'" and "'+todate+'"')
        context = {'ledgers': ledgers, 'fromdate':fromdate, 'todate': todate}
        # Create a Django response object, and specify content_type as pdf
        response = HttpResponse(content_type='application/pdf')
        #if direct download needed uncomment line below
        #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
        response['Content-Disposition'] = 'filename="report.pdf"'
        # find the template and render it.
        template = get_template(template_path)
        html = template.render(context)

        # create a pdf
        pisa_status = pisa.CreatePDF(
           html, dest=response)
        # if error then show some funy view
        if pisa_status.err:
           return HttpResponse('We had some errors <pre>' + html + '</pre>')
        return response


#LEDGER
@login_required(login_url='loginuser')
@admin_only
def home(request):
    #this edit to solve the MultiValueDictKeyError
    query = request.POST.get('query', False)
    if query == "":
        return render(request, 'ledger/home.html')
    alldealers = Dealer.objects.filter(name__istartswith=query)
    context = {'alldealers':alldealers}
    return render(request, 'ledger/home.html', context)

@login_required(login_url='loginuser')
@allowed_users(allowed_roles=['admin'])
def ledger(request, pk):
    dealer = Dealer.objects.get(id=pk)
    form = LedgerForm(initial={"dealer":dealer},instance=dealer)
    if request.method == 'GET':
        return render(request, 'ledger/ledger.html', {'form':form})
    else:
        form = LedgerForm(request.POST)
        print(form)
        if form.is_valid():
            # if not form.paymode == Cheque:
            # form.isChequeCleared = False
            form.save()
            return redirect('dealer', pk)

@login_required(login_url='loginuser')
@allowed_users(allowed_roles=['admin'])
def dealer(request, pk):
    dealer = Dealer.objects.get(id=pk)
    ledgers = dealer.ledger_set.all()
    orderedledger = ledgers.order_by('-date')

    #paginating
    p = Paginator(orderedledger, 10)
    page_num = request.GET.get('page', 1)
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)

    context = {'dealer':dealer, 'ledgers':ledgers,'orderedledger':page }
    return render(request, 'ledger/dealer.html', context)

@login_required(login_url='loginuser')
@allowed_users(allowed_roles=['admin'])
def dealerform(request):
    if request.method == 'GET':
        return render(request, 'ledger/dealerform.html', {'form':DealerForm()})
    else:
        form = DealerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')

@login_required(login_url='loginuser')
def userpage(request):
    try :
        userobjects = ViewDealer.objects.get(user=request.user)
        dealerallowed = userobjects.dealer.all()
    except :
        context = {"message": "No dealers allowed to view"}
        return render(request, 'ledger/user.html', context)
    # list l is storing data of all allowed dealer and their ledgers
    l = []
    for d in dealerallowed:
        dict = {}
        dict["name"] = d.name
        dict["address"] = d.address
        dict["mobile"] = d.mob_num
        #leg list for storing ledgers of the current iterating dealer
        leg = []
        bn = BrandNew.objects.get(dealer = d.id)
        led_number = bn.ledger_number
        k = 0
        while(k!=30):
            try:
                led = Ledger.objects.get(dealer = d,dealer_ledger_number = led_number-k)
                leg.append(led)
            except:
                break
            k += 1
        dict["ledger"] = leg
        l.append(dict)
    if len(dealerallowed) == 0:
        context = {"message": "No dealers allowed to view"}
    else:
        context = {"ledgers":l}
    return render(request, 'ledger/user.html', context)

def roadexpense(request):
    if request.method == 'GET':
        user = request.user
        form = RoadExpenseForm(initial={"user":user},instance=user)
        return render(request, 'ledger/expense.html', {'form':form})
    else:
        form = RoadExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')



# report to be converted into pdf from html
@login_required(login_url='loginuser')
@allowed_users(allowed_roles=['admin'])
def dailytrans(request):
    return render(request,'ledger/dailytrans.html')




# AUTHENTICATION FUNCTIONS

@unauthenticated_user
def loginuser(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request, 'ledger/home.html', {'form':AuthenticationForm(), 'error': 'Username or Password did not match'})
        else:
            login(request, user)
            return redirect('home')
    else:
        return render(request, 'ledger/login.html', {'form':AuthenticationForm()})


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('loginuser')

webledger-project/ledger/templates/ledger/base.html
{% load auth_extras %}
<!DOCTYPE html>
<html>
{% if user.is_authenticated %}
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
{% block css %}{% endblock %}
  <style>
        .logout-container {
          width: 50% ;
          display: flex;
          justify-content: end;
        }

        .item-container {
          display: flex;
        }

        @media only screen and (max-width: 1300px) {
          .item-left {
            margin: 0;
            padding: 0.5rem;
          }
        }

        @media only screen and (max-width: 991px) {
          .item-container {
            flex-direction: column;
            margin-top: 1rem;
          }

          .logout-container {
            width: 100% ;
            display: flex;
            justify-content: space-between;
          }

          .item-left {
            padding: 0.5rem;
          }
        }
  </style>
</head>


<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav" style="width:100%">
          {% if request.user|has_group:"admin" %}
          <div class="item-container" style="width:50%;">
            <a class="item-right nav-link" style="padding:0.5rem" href="{% url 'home' %}">Home</a>
            <a class="item-right nav-link" style="padding:0.5rem" href="{% url 'netbalpdf' %}">Dealer Report</a>
            <a class="item-right nav-link" style="padding:0.5rem" href="{% url 'dailytrans' %}">Transactions</a>
            {% else %}
            <a class="item-right nav-link" style="padding:0.5rem" href="{% url 'userpage' %}">Home</a>
            {% endif %}
            <a class="item-right nav-link" style="padding:0.5rem" href="{% url 'roadexpense' %}">Expense</a>
            {% if request.user.is_superuser %}
            <a class="item-right nav-link" style="padding:0.5rem" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
          </div>
          <div class="logout-container">
            <a class="item-left nav-link" style="color:#0d6efd; margin-right:1rem">Logged in as {{ user.username }}</a>
            <form style="margin-top:0px;" action="{% url 'logoutuser'  %}" method="POST">
                {% csrf_token %}

              <button class="btn btn-outline-success" type="submit" >Logout</button>
            </form>
          </div>

        </div>
      </div>
    </div>
  </nav>


{% block content %}{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script type="text/javascript">
  var q = document.getElementById("id_collect_by");
  //console.log(q) ;
  q.classList.add("form-select") ;
  q.options[0].innerHTML = "None";
</script>
</body>
{% endif %}
</html>

webledger-project/ledger/templates/ledger/dailytrans.html
{% extends 'ledger/base.html' %}
{% block title %}Transactions{% endblock %}
{% block content %}


  <body>




      <form method='POST' style="width:400px; margin:auto;" action="{% url 'day_range_rec' %}">
        <h1 style="padding-left:4.5rem; padding-top:1rem">Transactions</h1>
        {% if error %}
        <p class="alert alert-danger" role="alert">{{ error }}</p>
        {% endif %}
        {% csrf_token %}
        <div class="form-group" style="padding:0.5rem">
          <label style="padding-down:1rem">From:</label>
          <input class="form-control"  type="date" name="fromdate">
        </div>
        <div class="form-group" style="padding:0.5rem">
          <label style="padding-down:1rem">To:</label>
          <input class="form-control" type="date" name="todate">
        </div>
        <button class="btn btn-outline-primary" style="width:100px; margin:0.5rem;" type='submit'>GET PDF</button>

      </form>

      

  </body>



{% endblock %}

webledger-project/ledger/templates/ledger/day_range_rec.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Transactions PDF</title>
    <style>

      @page {
      size: "A4";
      margin: 1.5cm 1.5cm 3.5cm 1.5cm; }
      @top-center{
        content: "Dealer Balance";
      }
      @bottom-right {
        content: "page " counter() page " of  " counter(pages);
        }
      body {
        background-color:white;

  }





  th {
    font-size: 15px;

  }

  td {
    font-size: 12.5px;
  }
  table, th, td {
    text-align: center;
    padding-top: 5px;
    border: 1px solid black;
    border-collapse: collapse;
  }
  .dealer-col {
    width: 400px;
  }

  h1, h3 {
    text-align: center;
    padding: 0;
    margin:0;
  }
  h3 {
    font-weight: 200;
  }

  body {
    margin-top:5px;
    padding-top:5px;
  }




</style>
  </head>
  <body>

    <h1>Transactions from {{ fromdate }} to {{ todate }}</h1>


    <table repeat="1" class="table table-sm">

      <tr>
        <th>Dealer</th>
        <th>Date</th>
        <th>Particulars</th>
        <th>Mode</th>
        <th>Debit</th>
        <th>Credit</th>
        <th>Dr/Cr</th>
        <th>Balance</th>
      </tr>

      {% for ledger in ledgers %}
      <tr>
        <td>{{ ledger.dealer }}</td>
        <td>{{ ledger.date|date:"d M Y" }}  {{ ledger.date|time:"h:i A" }}</td>
        <td>{{ ledger.particulars }}</td>
        <td>{{ ledger.paymode }}</td>
        <td>{{ ledger.debit }}</td>
        <td>{{ ledger.credit }}</td>
        <td>{{ ledger.dr_cr }}</td>
        <td>{{ ledger.balance }}</td>
      </tr>
      {% endfor %}


      </table>

  </body>
</html>

webledger-project/ledger/templates/ledger/dealerform.html
{% extends 'ledger/base.html' %}
{% block content %}



<form method='POST' style="width:400px; margin:auto;">
{% csrf_token %}
  <h1 style="padding-left:1.5rem; padding-top:1rem">Create New Dealer</h1>

  <div class="form-group" style="padding:0.5rem">
    <label for="id_name" style="padding-down:1rem">Dealer Name</label>
    <input class="form-control" type="text" name="name" maxlength="200" required="" id="id_name">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_mob_num" style="padding-down:1rem">Dealer Number</label>
    <input class="form-control" type="number" name="mob_num" id="id_mob_num">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_address" style="padding-down:1rem">Address</label>
    <textarea class="form-control" name="address" cols="40" rows="10" id="id_address" style="height:150px"></textarea>
  </div>
  <button class="btn btn-outline-primary" style="width:100px; margin:0.5rem;" type='submit'>Save</button>

</form>

{% endblock %}

webledger-project/ledger/templates/ledger/expense.html
{% extends 'ledger/base.html' %}
{% block title %}Expense{% endblock %}
{% block content %}

<form method='POST' style="width:400px; margin:auto;">
  <h1 style="padding-left:4rem; padding-top:1rem">Road Expense</h1>
  <div style="display:none;">{{ form.user }}</div>
  {% csrf_token %}
  <div class="form-group" style="padding:0.5rem">
    <label for="id_fooding" style="padding-down:1rem">Fooding:</label>
    <input class="form-control"  type="number" name="fooding" value="0" min="0" id="id_fooding">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_fuel" style="padding-down:1rem">Fuel:</label>
    <input class="form-control" type="number" name="fuel" value="0" min="0" id="id_fuel">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_misc" style="padding-down:1rem">Misc:</label>
    <textarea class="form-control" style="height:150px" name="misc" cols="40" rows="10" id="id_misc"></textarea>
  </div>
  <button class="btn btn-outline-primary" style="width:100px; margin:0.5rem;" type='submit'>Save</button>

</form>

{% endblock %}

webledger-project/ledger/templates/ledger/ledger.html
{% extends 'ledger/base.html' %}
{% block content %}

<form method='POST' style="width:400px; margin:auto;">
  {% csrf_token %}
  <h1 style="padding-left:4rem; padding-top:1rem">Complete Entry</h1>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_particulars" style="padding-down:1rem">Particulars:</label>
    <input class="form-control" type="text" name="particulars" maxlength="100" id="id_particulars">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_debit" style="padding-down:1rem">Debit:</label>
    <input class="form-control" type="number" name="debit" value="0" min="0" id="id_debit">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_credit" style="padding-down:1rem">Credit:</label>
    <input class="form-control" type="number" name="credit" value="0" min="0" id="id_credit">
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_paymode" style="padding-down:1rem">Payment Mode:</label>
    <select class="form-control" name="paymode" required="" id="id_paymode">
      <option value="Cash" selected>Cash</option>
      <option value="Cheque">Cheque</option>
      <option value="No Money Collected">No Money Collected</option>
    </select>
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_invoice" style="padding-down:1rem">Invoice:</label>
    <input class="form-control" type="file" name="invoice" accept="image/*" id="id_invoice">
  </div>
  <div class="form-group" style="padding:0.5rem; display:none;">
    <label for="id_dealer" style="padding-down:1rem">Dealer:</label>
    {{ form.dealer }}
  </div>
  <div class="form-group" style="padding:0.5rem">
    <label for="id_collect_by" style="padding-down:1rem">Collected By:</label>
    {{ form.collect_by }}
  </div>

  <button class="btn btn-outline-primary" style="width:100px; margin:0.5rem;" type="submit">Save</button>

</form>
{% endblock %}

webledger-project/ledger/templates/ledger/user.html
{% extends 'ledger/base.html' %}
{% block content %}

{{ message }}

{% for ledger in ledgers %}
<p>Dealer Name: {{ ledger.name }}</p> <p>Address: {{ ledger.address}}</p>
<table class="table table-sm">
  <tr>
    <th>Date</th>
    <th>Particulars</th>
    <th>Invoice</th>
    <th>Mode</th>
    <th>Collected By</th>
    <th>Debit</th>
    <th>Credit</th>
    <th>Dr/Cr</th>
    <th>Balance</th>
  </tr>

  {% for l in ledger.ledger %}
  <tr>
    <td>{{ l.date }}</td>
    <td>{{ l.particulars }}</td>
    <td>{{ l.invoice }}</td>
    <td>{{ l.paymode }}</td>
    <td>{{ l.collect_by }}</td>
    <td>{{ l.debit }}</td>
    <td>{{ l.credit }}</td>
    <td>{{ l.dr_cr }}</td>
    <td>{{ l.balance }}</td>
  </tr>
  {% endfor %}

</table>
{% endfor %}

{% csrf_token %}


{% endblock %}